describe('Criação de uma nova oferta via comercializador', () => {
it('passes', () => {

        cy.login() 
        cy.get('.MuiButton-contained > .MuiButton-label').click()
        cy.get('#mui-component-select-type').click()
        cy.get('.MuiList-root > [tabindex="-1"]').click()
        cy.get('#mui-component-select-product_id').click()
        cy.get('[data-value="737377bd-4de2-4e8f-bf25-9f5aa9a4cf25"]').click()
        cy.get('#mui-component-select-modality_id').click()
        cy.get('[data-value="0f85a92b-a1b8-4c33-8dbd-757f695bca21"]').click()
        cy.get(':nth-child(3) > :nth-child(1) > .sc-pZnSc > .MuiFormControl-root > .MuiInputBase-root > .MuiInputBase-input').type('20')
        cy.get('#mui-component-select-currency_id').click()
        cy.get('.Mui-selected').click()
        cy.get('#mui-component-select-unit_of_measurement_id').click()
        cy.get('.MuiList-root > .MuiButtonBase-root').click()
        cy.get(':nth-child(4) > :nth-child(1) > .sc-pZnSc > .MuiFormControl-root > .MuiInputBase-root > .MuiInputBase-input').type('2')
        cy.get(':nth-child(2) > .sc-pZnSc > .MuiFormControl-root > .MuiInputBase-root > .MuiInputBase-input').type('10')
        cy.get('#mui-component-select-harvest_id').click()
        cy.get('[data-value="7279dcf4-9b1c-49f5-bd16-660fc7711060"]').click()
        cy.get(':nth-child(2) > [style="width: 100%;"] > .MuiFormControl-root > .MuiInputBase-root > .MuiInputBase-input').click()
        cy.get(':nth-child(6) > :nth-child(1) > .MuiButtonBase-root > .MuiIconButton-label').click()
        cy.get('.MuiDialogActions-root > :nth-child(2) > .MuiButton-label').click()
        cy.get(':nth-child(3) > [style="width: 100%;"] > .MuiFormControl-root > .MuiInputBase-root > .MuiInputBase-input').click()
        cy.get(':nth-child(6) > :nth-child(1) > .MuiButtonBase-root > .MuiIconButton-label').click()
        cy.get('.MuiDialogActions-root > :nth-child(2) > .MuiButton-label').click()
        cy.get('[style="margin-top: 10px; margin-bottom: 8px; width: 100%;"] > .MuiFormControl-root > .MuiInputBase-root > .MuiInputBase-input').click()
        cy.get(':nth-child(6) > :nth-child(1) > .MuiButtonBase-root > .MuiIconButton-label').click()
        cy.get('.MuiDialogActions-root > :nth-child(2) > .MuiButton-label').click()
        cy.get('#mui-component-select-shipping').click()
        cy.get('.MuiList-root > :nth-child(2)').click()
        cy.get('#mui-component-select-delivery_place').click()
        cy.get('.MuiList-root > [tabindex="-1"]').click()
        cy.get('[style="margin-top: 10px; padding-bottom: 8px;"] > :nth-child(1) > .MuiFormControl-root > .MuiInputBase-root > .MuiInputBase-input').click()
        cy.get(':nth-child(6) > :nth-child(1) > .MuiButtonBase-root > .MuiIconButton-label > .MuiTypography-root').click()
        cy.get('.MuiDialogActions-root > :nth-child(2) > .MuiButton-label').click()
        cy.get('[style="margin-top: 10px; padding-bottom: 8px;"] > :nth-child(2) > .MuiFormControl-root > .MuiInputBase-root > .MuiInputBase-input').click()
        cy.get('.MuiDialogActions-root > :nth-child(2) > .MuiButton-label').click()
        cy.get(':nth-child(10) > .MuiGrid-root > .sc-pZnSc > .MuiFormControl-root > .MuiInputBase-root > .MuiInputBase-input').type('teste')
        cy.get('.MuiGrid-justify-xs-flex-end > .MuiButtonBase-root').click()
        cy.get('#mui-component-select-state').click()
        cy.get('[data-value="22ee6d2d-68a9-400a-bb09-a0f865aa2955"]').click()
        cy.get(':nth-child(2) > .MuiListItemIcon-root > .MuiButtonBase-root > .MuiIconButton-label > .jss100').click()
        cy.get('.MuiButton-label').click()
        cy.get(':nth-child(1) > .MuiButtonBase-root > .MuiButton-label').click()
        cy.get(':nth-child(3) > .MuiButtonBase-root > .MuiButton-label').click()   
      })})