describe('Criação de uma nova oferta via produtor', () => {
    it('passes', () => {
        cy.visit('https://www.homolog.backoffice.poc.tech/')
        cy.get('div[class*="sc-AxhCb"]').should('be.visible').should('have.text', 'poc')
        cy.get('input[name="username"]').type('613.810.200-20')
        cy.get(':nth-child(2) > .MuiFormControl-root > .MuiInputBase-root > .MuiInputBase-input').type('poc1234')
        cy.get('#demo-simple-select').click()
        cy.get('[data-value="PRODUCER"]').click()
        cy.get('.MuiButton-label').click()
        cy.get('.sc-AxhUy')
        cy.get('.MuiButton-contained > .MuiButton-label').click()
        cy.get('#mui-component-select-product_id').click()
        cy.get('[data-value="737377bd-4de2-4e8f-bf25-9f5aa9a4cf25"]').click()
        cy.get('#mui-component-select-modality_id').click()
        cy.get('[data-value="e546a0b5-f32e-4787-a5ca-9104664c1ba5"]').click()
        cy.get(':nth-child(3) > :nth-child(1) > .sc-pZnSc > .MuiFormControl-root > .MuiInputBase-root > .MuiInputBase-input').type('30')
        cy.get('#mui-component-select-unit_of_measurement_id').click()
        cy.get('.MuiList-root > .MuiButtonBase-root').click()
        cy.get(':nth-child(4) > :nth-child(1) > .sc-pZnSc > .MuiFormControl-root > .MuiInputBase-root > .MuiInputBase-input').type('4')
        cy.get(':nth-child(2) > .sc-pZnSc > .MuiFormControl-root > .MuiInputBase-root > .MuiInputBase-input').type('30')
        cy.get('#mui-component-select-harvest_id').click()
        cy.get('[data-value="7279dcf4-9b1c-49f5-bd16-660fc7711060"]').click()
        cy.get('[style="margin-top: 10px; margin-bottom: 8px; width: 100%;"] > .MuiFormControl-root > .MuiInputBase-root > .MuiInputBase-input').click()
        cy.get('.MuiDialogActions-root > :nth-child(2) > .MuiButton-label').click()
        cy.get('#mui-component-select-delivery_place').click()
        cy.get('[data-value="434eeb05-c4aa-46e9-a8ba-bda8fe519cd7"]').click()
        cy.get('[style="margin-top: 10px; padding-bottom: 8px;"] > :nth-child(1) > .MuiFormControl-root > .MuiInputBase-root > .MuiInputBase-input').click()
        cy.get(':nth-child(5) > :nth-child(3) > .MuiButtonBase-root > .MuiIconButton-label > .MuiTypography-root').click()
        cy.get('.MuiDialogActions-root > :nth-child(2) > .MuiButton-label').click()
        cy.get(':nth-child(9) > .MuiGrid-root > .sc-pZnSc > .MuiFormControl-root > .MuiInputBase-root > .MuiInputBase-input').type('teste nova oferta via produtor')
        cy.get('.MuiButton-label').click()
        cy.get(':nth-child(2) > .MuiListItemIcon-root > .MuiButtonBase-root > .MuiIconButton-label > .jss149').click()
        cy.get('.MuiButton-label').click()
        cy.get(':nth-child(1) > .MuiButtonBase-root > .MuiButton-label').click()



    })})